version: 2

registries:
  jetbrains-compose:
    type: maven-repository
    url: https://maven.pkg.jetbrains.space/public/p/compose/dev

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-all:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - jetbrains-compose
    schedule:
      interval: "daily"
    groups:
      gradle-all:
        patterns:
          - "*"